title: MyGallery
subtitle: 
description: 
author: Breeze

footer_logo: 
  use: self
  self:
    link: 'https://github.com/KingLear1606'
    src: 'https://github.com/lfkdsk/picx-images-hosting/raw/master/20230817/tripper2white.2pbuwaqvndu0.webp'

url: https://kinglear1606.github.io/Gallery
root: /Gallery

photography_page:
  slogan: true
  slogan_descr: '影像随心'

google_analytics: 
  use: gtag
  ga_id: 
  ga_api: 
  gtag_id: XXXXX
  
follow_challenge:
  feedId: ""
  userId: ""
  
nav:
  归档: 
    link: https://github.com/KingLear1606/Gallery
    icon: inbox

  地图:
    link: /Gallery/location
    icon: local-two

  随机:
    link: /Gallery/random
    icon: pic
  # 查询:
  #   link: /gallery/query
  #   icon: history-query
  状态监控:
    link: /Gallery/status
    icon: list-view
  时间线:
    link: /Gallery/grid-all
    icon: grid-nine

thumbnail_url: https://cdn.jsdelivr.net/gh/KingLear1606/Gallery@thumbnail/
base_url: https://cdn.jsdelivr.net/gh/KingLear1606/Gallery@master

backup_base_url: https://raw.githubusercontent.com/KingLear1606/Gallery/master
backup_thumbnail_url: https://raw.githubusercontent.com/KingLear1606/Gallery/thumbnail/
