title: MyGallery
subtitle: 
description: 
author: Breeze

footer_logo: 
  use: self
  self:
    link: 'https://github.com/KingLear1606'
    src: 'https://github.com/lfkdsk/picx-images-hosting/raw/master/20230817/tripper2white.2pbuwaqvndu0.webp'

url: https://kinglear1606.github.io/Gallery/
root: /Gallery

photography_page:
  slogan: true
  slogan_descr: '影像随心'

google_analytics: 
  use: gtag
  ga_id: 
  ga_api: 
  gtag_id: XXXXX

nav:
  归档: 
    link: https://github.com/KingLear1606/Gallery
    icon: inbox

thumbnail_url: https://cdn.jsdelivr.net/gh/KingLear1606/Gallery@thumbnail/
base_url: https://cdn.jsdelivr.net/gh/KingLear1606/Gallery@master
